version: '3.8'

services:
  apache-reverse-proxy:
    build: .
    image: apache-reverse-proxy:latest
    container_name: ${CONTAINER_NAME:-apache-reverse-proxy}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      # Apache2 Konfiguration
      - ./config/sites-available:/etc/apache2/sites-available
      - ./config/sites-enabled:/etc/apache2/sites-enabled
      - ./config/conf-available:/etc/apache2/conf-available
      - ./config/conf-enabled:/etc/apache2/conf-enabled
      - ./config/mods-available:/etc/apache2/mods-available
      - ./config/mods-enabled:/etc/apache2/mods-enabled
      
      # Let's Encrypt Zertifikate (persistent)
      - letsencrypt:/etc/letsencrypt
      
      # Apache2 Logs (optional)
      - ./logs:/var/log/apache2
      
      # Webroot für Let's Encrypt Challenge (falls benötigt)
      - ./webroot:/var/www/html
    environment:
      - TZ=${TZ:-Europe/Berlin}
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
      net.ipv6.conf.all.accept_ra: 2
      net.ipv6.conf.default.accept_ra: 2
      net.ipv6.conf.all.autoconf: 1
      net.ipv6.conf.default.autoconf: 1
    networks:
      - proxy-network
      - lan-ipv6

volumes:
  letsencrypt:
    name: apache-letsencrypt

networks:
  proxy-network:
    driver: bridge
    name: ${NETWORK_NAME:-apache-proxy-network}
  lan-ipv6:
    driver: macvlan
    name: ${IPV6_LAN_NETWORK_NAME:-apache-lan-ipv6}
    driver_opts:
      parent: ${PARENT_IFACE:-eth0}