version: '3.8'

services:
  apache-reverse-proxy:
    build: .
    image: apache-reverse-proxy:latest
    container_name: ${CONTAINER_NAME:-apache-reverse-proxy}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      # Apache2 Konfiguration
      - ./config/sites-available:/etc/apache2/sites-available:ro
      - ./config/sites-enabled:/etc/apache2/sites-enabled:ro
      - ./config/conf-available:/etc/apache2/conf-available:ro
      - ./config/conf-enabled:/etc/apache2/conf-enabled:ro
      - ./config/mods-available:/etc/apache2/mods-available:ro
      - ./config/mods-enabled:/etc/apache2/mods-enabled:ro
      
      # Let's Encrypt Zertifikate (persistent)
      - letsencrypt:/etc/letsencrypt
      
      # Apache2 Logs (optional)
      - ./logs:/var/log/apache2
      
      # Webroot für Let's Encrypt Challenge (falls benötigt)
      - ./webroot:/var/www/html
    environment:
      - TZ=${TZ:-Europe/Berlin}
    networks:
      - proxy-network

volumes:
  letsencrypt:
    name: apache-letsencrypt

networks:
  proxy-network:
    driver: bridge
    name: ${NETWORK_NAME:-apache-proxy-network}